"""add feature_flags to organization

Revision ID: 2702640c1df4
Revises: 002_phase6_alter_existing_tables
Create Date: 2026-07-06 17:50:51.757717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2702640c1df4'
down_revision: Union[str, None] = '002_phase6_alter_existing_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('feature_flags', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'feature_flags')
    # ### end Alembic commands ###
